# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LedgeDesign
email: ledgedesign@me.com
description: > # this means to ignore newlines until "baseurl:"
  A Selected Collection of Various Work, Professional & Personal 
baseurl: "/Home" # the subpath of your site, e.g. /blog
url: "https://ledgedesign.github.io" # the base hostname & protocol for your site
# twitter_username: druthers
github_username:  LedgeDesign

collections:
  illustration:
    output: true
  drawings:
    output: true
  setdesigns:
    output: true
  branding:
    output: true

# Build settings
markdown: kramdown
permalink: pretty
